---
- name: Install Ruby and Bundler
  hosts: all
  become: true
  vars:
    packages:
      - ruby-full
      - ruby-bundler
      - build-essential
  tasks:
  - name: Update apt cache
    apt: update_cache=yes

  - name: Install Ruby and required packages
    apt:
      name: "{{ packages }}"
      state: present
