plugin: gcp_compute
projects:
  - infra-271013
regions:
  - europe-west1-b
filters: []
hostnames:
  - name
groups:
  app: "'reddit-app' in name"
  db: "'reddit-db' in name"
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
auth_kind: serviceaccount
service_account_file: ~/projects/devops/infra-sa.json
